"""Scout report models for the startup opportunity scout.

Structured daily reports covering tech trends, user complaints,
industry gaps, and actionable startup ideas sourced from the web.
"""

from __future__ import annotations

from datetime import date, datetime
from enum import Enum

from pydantic import BaseModel, Field


class TrendSource(str, Enum):
    """Source where a tech trend was identified."""

    GOOGLE_TRENDS = "google_trends"
    EXPLODING_TOPICS = "exploding_topics"
    HACKER_NEWS = "hacker_news"
    PRODUCT_HUNT = "product_hunt"
    REDDIT = "reddit"
    TWITTER = "twitter"
    TECHCRUNCH = "techcrunch"
    OTHER = "other"


class ComplaintSource(str, Enum):
    """Source where a user complaint was found."""

    REDDIT = "reddit"
    TWITTER = "twitter"
    APP_STORE = "app_store"
    GOOGLE_PLAY = "google_play"
    TRUSTPILOT = "trustpilot"
    CONSUMER_AFFAIRS = "consumer_affairs"
    BBB = "bbb"
    AMAZON = "amazon"
    LINKEDIN = "linkedin"
    HACKER_NEWS = "hacker_news"
    OTHER = "other"


class TechTrend(BaseModel):
    """A trending technology topic detected from web sources."""

    id: str
    title: str
    description: str = ""
    evidence: str = ""
    sources: list[TrendSource] = Field(default_factory=list)
    source_urls: list[str] = Field(default_factory=list)
    interest_score: float = Field(default=0.0, ge=0.0, le=1.0)
    growth_rate: str = ""  # e.g. "+120% in 30 days"
    related_keywords: list[str] = Field(default_factory=list)

    def is_significant(self) -> bool:
        """Return True if the trend is significant enough to report."""
        return self.interest_score >= 0.5 and bool(self.evidence)


class UserComplaint(BaseModel):
    """A user complaint or pain point extracted from the web."""

    id: str
    summary: str
    detail: str = ""
    source: ComplaintSource = ComplaintSource.OTHER
    source_url: str = ""
    quote: str = ""  # Direct user quote
    product_or_category: str = ""
    severity: float = Field(default=0.5, ge=0.0, le=1.0)
    frequency: str = ""  # e.g. "mentioned 50+ times this week"
    detected_at: datetime | None = None

    def is_actionable(self) -> bool:
        """Return True if this complaint reveals a clear gap."""
        return self.severity >= 0.5 and bool(self.summary)


class IndustryGap(BaseModel):
    """An identified industry gap with supporting data."""

    id: str
    title: str
    description: str = ""
    market_size: str = ""  # e.g. "$5B TAM"
    demand_evidence: str = ""
    supply_assessment: str = ""  # e.g. "Only 2 competitors, both poorly rated"
    data_sources: list[str] = Field(default_factory=list)
    opportunity_score: float = Field(default=0.0, ge=0.0, le=1.0)

    def is_viable(self) -> bool:
        """Return True if this gap represents a viable opportunity."""
        return self.opportunity_score >= 0.5 and bool(self.demand_evidence)


class ScoutStartupIdea(BaseModel):
    """A startup idea generated by the opportunity scout."""

    id: str
    title: str
    description: str = ""
    target_market: str = ""
    why_it_fills_gap: str = ""
    potential_impact: str = ""  # e.g. "High — addresses $2B market gap"
    tech_stack: list[str] = Field(default_factory=list)
    monetization: str = ""
    feasibility: str = ""  # "low", "medium", "high"
    related_trend_ids: list[str] = Field(default_factory=list)
    related_complaint_ids: list[str] = Field(default_factory=list)
    related_gap_ids: list[str] = Field(default_factory=list)


class SourceSummary(BaseModel):
    """Summary of a single data source queried during the scout run."""

    source_name: str
    url: str = ""
    items_found: int = 0
    key_finding: str = ""
    status: str = "success"  # "success", "partial", "failed", "unavailable"


class ScoutReport(BaseModel):
    """Complete daily startup opportunity scout report."""

    date: date
    headline: str = ""
    tech_trends: list[TechTrend] = Field(default_factory=list)
    complaints: list[UserComplaint] = Field(default_factory=list)
    industry_gaps: list[IndustryGap] = Field(default_factory=list)
    startup_ideas: list[ScoutStartupIdea] = Field(default_factory=list)
    sources_summary: list[SourceSummary] = Field(default_factory=list)

    def total_signals(self) -> int:
        """Return the total number of items in the report."""
        return (
            len(self.tech_trends)
            + len(self.complaints)
            + len(self.industry_gaps)
            + len(self.startup_ideas)
        )

    def build_headline(self) -> None:
        """Generate the report headline from its contents."""
        parts: list[str] = []
        if self.tech_trends:
            parts.append(f"{len(self.tech_trends)} trends")
        if self.complaints:
            parts.append(f"{len(self.complaints)} complaints")
        if self.industry_gaps:
            parts.append(f"{len(self.industry_gaps)} gaps")
        if self.startup_ideas:
            parts.append(f"{len(self.startup_ideas)} ideas")
        summary = ", ".join(parts) if parts else "No signals"
        self.headline = (
            f"Scout Report — {self.date.strftime('%B %d, %Y')}: {summary}"
        )
